/*
 * generated by Xtext 2.31.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.templ.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class TemplWebModule extends AbstractTemplWebModule {
}
