/*
 * generated by Xtext 2.31.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.templ.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TemplUiModule extends AbstractTemplUiModule {

	public TemplUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
