/*
 * generated by Xtext 2.31.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.templ.ide;

import com.epistimis.face.templ.TemplRuntimeModule;
import com.epistimis.face.templ.TemplStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TemplIdeSetup extends TemplStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TemplRuntimeModule(), new TemplIdeModule()));
	}
	
}
