/*
 * generated by Xtext 2.31.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.templ.formatting2

//import com.epistimis.face.templ.services.TemplGrammarAccess
import com.epistimis.face.templ.templ.TemplateSpecification
import com.epistimis.face.templ.templ.UsingExternalTemplateStatement
//import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class TemplFormatter extends AbstractFormatter2 {
	
//	@Inject extension TemplGrammarAccess

	def dispatch void format(TemplateSpecification templateSpecification, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (usingExternalTemplateStatement : templateSpecification.usingExternalTemplateStatement) {
			usingExternalTemplateStatement.format
		}
		for (structuredTemplateElementTypeDecl : templateSpecification.structuredTemplateElementTypeDecl) {
			structuredTemplateElementTypeDecl.format
		}
	}

	def dispatch void format(UsingExternalTemplateStatement usingExternalTemplateStatement, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		usingExternalTemplateStatement.externalTemplateTypeReference.format
	}
	
	// TODO: implement for MainEntityTypeTemplateMethodDecl, OptionalEntityTypeTemplateMethodParameterList, MainEquivalentEntityTypeTemplateMethodDecl, SupportingEntityTypeTemplateMethodDecl, SupportingEquivalentEntityTypeTemplateMethodDecl, EntityTypeTemplateMethodBody, EquivalentEntityTypeTemplateMethodDecl, EquivalentEntityTypeTemplateMethodParameterList, EquivalentEntityTypeTemplateMethodBody, EquivalentEntityTypeTemplateMethodMember, EquivalentEntityTypeTemplateElementMemberStatement, UnionTypeDecl, UnionBody, UnionSwitchStatement, UnionSwitchBody, CaseExpression, CaseLabel, UnionMember, EntityTypeStructuredTemplateElementMember, ExplicitDesignatedEntityNonEntityTypeCharacteristicReferenceExpression, StructuredTemplateElementTypeReferenceStatement, StructuredTemplateElementTypeReferenceExpression, StructuredTemplateElementTypeReferenceParameterList, StructuredTemplateElementTypeReferenceParameter, EntityTypeStructuredTemplateElementDeclaredParameterExpression, DesignatedEquivalentEntityNonEntityTypeCharacteristicReference, DesignatedEntityNonEntityTypeCharacteristicReference, DesignatedEntityNonEntityTypeCharacteristicWildcardReference, DesignatedEntityEnumerationTypeCharacteristicReference, DesignatedEntityTypeReferencePath, ExplicitEntityTypeReferenceJoinPath, QualifiedEntityTypeReference, EnumLiteralReferenceExpression
}
