/*
 * generated by Xtext 2.31.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.templ;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TemplRuntimeModule extends AbstractTemplRuntimeModule {
}
