/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.templ.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link TemplWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractTemplWebModule extends DefaultWebModule {

}
